KeyCrypterException: Introduce dedicated PublicPrivateMismatch exception for when a private key or seed is decrypted, it doesn't match its public key.